version: '3'
services:
    postgres:
        image: 'postgres:latest'
        environment:
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_DB=simple_blog_api
    
    api:
        depends_on:
            - postgres
        image: pothugantianil95/simple_blog_api
        ports: 
            -  '3000:3000'
        build:
            context: ./
            dockerfile: Dockerfile.dev
        environment:
            - POSTGRES_USERNAME=postgres
            - POSTGRES_HOST=postgres
            - PGDATABASE=simple_blog_api
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_PORT=5432